### PR TITLE
Add new option "cycleImages"

### PR DESCRIPTION
**Pull request by Zerogiven**
To cycle the gallery now we are able to set cycleImages as true/false option

### CODE REVIEW

**Comment by gertsonderby** [comment]
Hmm, not crazy about the `variable === false`pattern. Please use `!variable` instead - and remove the `=== true` as well. Otherwise, with that changed, it looks good, I wouldn't feel bad about merging.

**Comment by Zerogiven** [comment]
I do `variable === false` cause the `===` is for type checking... otherwise var could be 0 and you also get a true condition at `!variable`.

However, it isn't a mistake if you get there a zero or a false or an empty string :)

And thx at all, will use your plugin for my next web project (y)

**Comment by Zerogiven** [comment]
Hmm sorry i just found a little bug, don't have time now, but maybe you can find the mistake.

If i open the shinybox and start sliding to the right, cycling the images are no problem, no matter which direction.

But if i start sliding to the left, first i got a blank image, and it does not work till i first slide to the right.

So i think my mistake is somewhere inside the "prev" function ;) Not really sure at the moment why it does work sliding to the left side(and cycling too) after sliding to the right :)

**Comment by avcs06** [comment]
This feature is implemented in #27

**Pull request closed without merging**
